# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and test noobos
on:
  workflow_run:
    workflows: ["Create and publish Docker image"]
      types:
        - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    contianer: 
      image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      volumes: ${{ env.GITHUB_WORKSPACE }}:/home/devuser/noobos 
      options: -u devuser
    steps:
        uses: actions/checkout@v2
      - name: build and test
        run: make clean
        run: make all
      - name: clang-tidy check
        run: make clean
        run: bear make all
        run: find . -name '*.cpp' -o -name '*.h' -o -name '*.hpp' | xargs clang-tidy -p . > clang_tidy.out
        if: [[ !  -s clang_tidy.out ]] # not empty
          run: echo "clang-tidy failed"
          run: cat clang_tidy.out
          run: exit 1