# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: Build and test noobos
on:
  workflow_run:
    workflows: ["Create and publish Docker image"]
    types: [completed]
jobs:
  build-and-test:
    name: "Build and test"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tn259/noobos:${{ github.ref_name }}
      options: -u devuser -v ./:/home/devuser/noobos
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          make clean
          make all
      - name: clang-tidy-check
        run: |
          make clean && bear make all
          find . -name '*.cpp' -o -name '*.h' -o -name '*.hpp' | xargs clang-tidy -p . > clang_tidy.out
          if [[ ! -s clang_tidy.out ]]; then # not empty
            echo "clang-tidy failed"
            cat clang_tidy.out
            exit 1
          fi
      - name: test
        run: ./test_boot_i386.sh
